using System;
using System.Linq;
using System.Reactive.Linq;
using System.Reflection;
using Avalonia.Controls.Notifications;
using Microsoft.Extensions.DependencyInjection;
using TestApp.Samples.Navigation;
using TestApp.Shell;
using Zafiro.Avalonia.Dialogs;
using Zafiro.Avalonia.Misc;
using Zafiro.Avalonia.Services;
using Zafiro.UI;
using Zafiro.UI.Navigation;
using Zafiro.UI.Shell;
using Zafiro.UI.Shell.Utils;
using ReactiveUI;

namespace TestApp;

public static class CompositionRoot
{
    public static MainViewModel Create()
    {
        ServiceCollection services = new();

        services.AddSingleton<IShell, Zafiro.UI.Shell.Shell>();
        services.AddSingleton(new ShellProperties("Avalonia.Zafiro Tookit", navigatorObj => CreateHeaderFromNavigator(navigatorObj)));
        services.AddSingleton(DialogService.Create());
        // Defer NotificationService initialization until TopLevel is available (Loaded)
        var topLevel = ApplicationUtils.TopLevel().GetValueOrThrow("TopLevel not ready for NotificationService");
        var notificationManager = new WindowNotificationManager(topLevel) { Position = NotificationPosition.BottomRight };
        services.AddSingleton<INotificationService>(new NotificationService(notificationManager));
        // Ensure DI registrations for annotated sections (generated by Zafiro.Avalonia.Generators)
        services.RegisterAnnotatedSections();

        // Register sections with visual group headers for desktop pane; mobile layout remains flat.
        services.RegisterSections(builder =>
        {
            var assembly = typeof(App).Assembly;
            var annotated = from t in assembly.GetTypes()
                            let attr = t.GetCustomAttributes(typeof(Zafiro.UI.Shell.Utils.SectionAttribute), inherit: false).Cast<Zafiro.UI.Shell.Utils.SectionAttribute>().FirstOrDefault()
                            where t.IsClass && !t.IsAbstract && t.Name.EndsWith("ViewModel") && attr is not null
                            select new { Type = t, Attr = attr };

            // Group by top-level folder under Samples (namespace segment after 'Samples')
            var groups = annotated
                .Select(s => new
                {
                    SectionType = s.Type,
                    s.Attr,
                    Group = GetTopLevelGroupName(s.Type)
                })
                .GroupBy(x => x.Group)
                .OrderBy(g => g.Key);

            foreach (var group in groups)
            {
                builder.Group(group.Key, b =>
                {
                    foreach (var item in group.OrderBy(x => x.Attr.SortIndex).ThenBy(x => x.SectionType.Name))
                    {
                        var name = item.Attr.Name ?? ToSpaced(TrimSuffix(item.SectionType.Name, "ViewModel"));
                        var icon = new Zafiro.UI.Icon(item.Attr.Icon ?? "fa-window-maximize");
                        var method = typeof(SectionsBuilder).GetMethod("Add")!.MakeGenericMethod(item.Attr.ContractType ?? item.SectionType);
                        method.Invoke(b, new object[] { name, icon, true });
                    }
                });
            }
        }, scheduler: RxApp.MainThreadScheduler);

        services.AddTransient<MainViewModel>();
        services.AddTransient<TargetViewModel>();

        var serviceProvider = services.BuildServiceProvider();

        return serviceProvider.GetRequiredService<MainViewModel>();
    }

    private static IObservable<object?> CreateHeaderFromNavigator(object navigatorObj)
    {
        var navigator = (INavigator)navigatorObj;
        return navigator.Content.Select(o =>
        {
            var type = o?.GetType();

            var s = type?.GetCustomAttribute<SectionAttribute>()?.Name;
            if (s != null)
            {
                return s;
            }

            if (type is null)
            {
                return "Unknown Section";
            }

            return GetSectionName(type);
        });
    }

    private static string GetSectionName(Type getType)
    {
        string sectionName = getType.Name.Replace("ViewModel", "");
        string formattedName = string.Concat(sectionName.Select(x => char.IsUpper(x) ? " " + x : x.ToString())).TrimStart(' ');
        return formattedName;
    }

    private static string GetTopLevelGroupName(Type type)
    {
        // Expect namespaces like TestApp.Samples.<Group>.*; fallback to "Samples"
        var ns = type.Namespace ?? string.Empty;
        var parts = ns.Split('.');
        var samplesIndex = Array.IndexOf(parts, "Samples");
        if (samplesIndex >= 0 && samplesIndex + 1 < parts.Length)
        {
            return parts[samplesIndex + 1];
        }
        // Fallbacks: Shell, etc.
        if (parts.Length >= 2)
        {
            return parts[^1];
        }
        return "Samples";
    }

    private static string TrimSuffix(string s, string suffix) => s.EndsWith(suffix, StringComparison.Ordinal) ? s.Substring(0, s.Length - suffix.Length) : s;
    private static string ToSpaced(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        var sb = new System.Text.StringBuilder();
        for (int i = 0; i < name.Length; i++)
        {
            var ch = name[i];
            if (i > 0 && char.IsUpper(ch) && !char.IsWhiteSpace(name[i - 1])) sb.Append(' ');
            sb.Append(ch);
        }
        return sb.ToString().TrimStart(' ');
    }
}